# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Measure(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, code: str=None, fecha_muestreo: str=None, unidad: str=None, tipo: str=None, medicion: str=None):  # noqa: E501
        """Measure - a model defined in Swagger

        :param code: The code of this Measure.  # noqa: E501
        :type code: str
        :param fecha_muestreo: The fecha_muestreo of this Measure.  # noqa: E501
        :type fecha_muestreo: str
        :param unidad: The unidad of this Measure.  # noqa: E501
        :type unidad: str
        :param tipo: The tipo of this Measure.  # noqa: E501
        :type tipo: str
        :param medicion: The medicion of this Measure.  # noqa: E501
        :type medicion: str
        """
        self.swagger_types = {
            'code': str,
            'fecha_muestreo': str,
            'unidad': str,
            'tipo': str,
            'medicion': str
        }

        self.attribute_map = {
            'code': 'code',
            'fecha_muestreo': 'fechaMuestreo',
            'unidad': 'unidad',
            'tipo': 'tipo',
            'medicion': 'medicion'
        }

        self._code = code
        self._fecha_muestreo = fecha_muestreo
        self._unidad = unidad
        self._tipo = tipo
        self._medicion = medicion

    @classmethod
    def from_dict(cls, dikt) -> 'Measure':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Measure of this Measure.  # noqa: E501
        :rtype: Measure
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> str:
        """Gets the code of this Measure.


        :return: The code of this Measure.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """Sets the code of this Measure.


        :param code: The code of this Measure.
        :type code: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def fecha_muestreo(self) -> str:
        """Gets the fecha_muestreo of this Measure.


        :return: The fecha_muestreo of this Measure.
        :rtype: str
        """
        return self._fecha_muestreo

    @fecha_muestreo.setter
    def fecha_muestreo(self, fecha_muestreo: str):
        """Sets the fecha_muestreo of this Measure.


        :param fecha_muestreo: The fecha_muestreo of this Measure.
        :type fecha_muestreo: str
        """
        if fecha_muestreo is None:
            raise ValueError("Invalid value for `fecha_muestreo`, must not be `None`")  # noqa: E501

        self._fecha_muestreo = fecha_muestreo

    @property
    def unidad(self) -> str:
        """Gets the unidad of this Measure.


        :return: The unidad of this Measure.
        :rtype: str
        """
        return self._unidad

    @unidad.setter
    def unidad(self, unidad: str):
        """Sets the unidad of this Measure.


        :param unidad: The unidad of this Measure.
        :type unidad: str
        """
        if unidad is None:
            raise ValueError("Invalid value for `unidad`, must not be `None`")  # noqa: E501

        self._unidad = unidad

    @property
    def tipo(self) -> str:
        """Gets the tipo of this Measure.


        :return: The tipo of this Measure.
        :rtype: str
        """
        return self._tipo

    @tipo.setter
    def tipo(self, tipo: str):
        """Sets the tipo of this Measure.


        :param tipo: The tipo of this Measure.
        :type tipo: str
        """
        if tipo is None:
            raise ValueError("Invalid value for `tipo`, must not be `None`")  # noqa: E501

        self._tipo = tipo

    @property
    def medicion(self) -> str:
        """Gets the medicion of this Measure.


        :return: The medicion of this Measure.
        :rtype: str
        """
        return self._medicion

    @medicion.setter
    def medicion(self, medicion: str):
        """Sets the medicion of this Measure.


        :param medicion: The medicion of this Measure.
        :type medicion: str
        """
        if medicion is None:
            raise ValueError("Invalid value for `medicion`, must not be `None`")  # noqa: E501

        self._medicion = medicion
